Repository Network-office/Network-office-FE, pull requests merged in 2024-10, with the labels that each got.

#108 feat: 카카오 로그인 연결 완료
  .gitignore
  jest.polyfills.js
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/successLogin.jpg
  src/app/api/auth/[...nextauth]/route.ts
  src/app/kakao/_api/auth/csrf/index.ts
  src/app/kakao/_components/AvatarForm.tsx
  src/app/kakao/_components/NickNameForm.tsx
  src/app/kakao/_components/PhoneInputModal.tsx
  src/app/kakao/_components/SuccessLogin.tsx
  src/app/kakao/_context/signinContext.tsx
  src/app/kakao/_hooks/_mutations/useGeneratePhoneVerfification.tsx
  src/app/kakao/_hooks/_mutations/useKakaoMutation.ts
  src/app/kakao/_hooks/_mutations/useVerifiyPhone.ts
  src/app/kakao/_hooks/_queries/useGetUserInfo.ts
  src/app/kakao/_hooks/_useAvatarForm.ts
  src/app/kakao/constants.ts
  src/app/kakao/login/[socialid]/page.tsx
  src/app/kakao/login/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/mypage/_api/getUserInform.ts
  src/app/mypage/_componets/MyPageMenuSection.tsx
  src/app/mypage/_hooks/_quries/useGetUserInform.ts
  src/app/mypage/page.tsx
  src/app/mypage/types.ts
  src/mock/api/meetingApi.js
  src/mock/mockData/pariticpateData.ts
Labels: ✨Feature

#102 feat: 채팅리스트 와 채팅 페이지 로딩및 에러처리
  src/_common/_components/SkeletonLoader.tsx
  src/_common/_components/Topbar.tsx
  src/app/chat/[chatId]/_components/skeletons/MyMessageGroupSkeleton.tsx
  src/app/chat/[chatId]/_components/skeletons/OtherMessageGroupSkeleton.tsx
  src/app/chat/[chatId]/_hooks/useFetchChatHistory.ts
  src/app/chat/[chatId]/layout.tsx
  src/app/chat/[chatId]/loading.tsx
  src/app/chat/[chatId]/page.tsx
  src/app/chat/_apis/getChatRoomList.ts
  src/app/chat/_components/ChatRoomList.tsx
  src/app/chat/_components/ChatRoomListWithTabs.tsx
  src/app/chat/_components/skeletons/ChatRoomItemSkeleton.tsx
  src/app/chat/_components/skeletons/ChatRoomListSkeleton.tsx
  src/app/chat/_hooks/queries/useGetChatRoomList.ts
  src/app/chat/page.tsx
  src/stories/Skeleton.stories.tsx
Labels: ✨Feature

#104 feat : 동호회 메인 홈 페이지 구현
  next.config.js
  package.json
  pnpm-lock.yaml
  public/icon/book.png
  public/icon/coffee.png
  public/icon/culture.png
  public/icon/field.png
  public/icon/music.png
  public/icon/sport.png
  public/icon/travel.png
  public/icon/volunteer.png
  src/_common/_hooks/useFunnel/index.tsx
  src/app/club/_api/getLocalClubs.ts
  src/app/club/_api/getNewClubs.tsx
  src/app/club/_components/ClubGenreList.tsx
  src/app/club/_components/ClubHeader.tsx
  src/app/club/_components/ClubListErrorFallback.tsx
  src/app/club/_components/ClubSearchBar.tsx
  src/app/club/_components/LocalClubList.stories.tsx
  src/app/club/_components/LocalClubList.tsx
  src/app/club/_components/LocalClubListItem.tsx
  src/app/club/_components/NewClubList.tsx
  src/app/club/_components/NewClubListItem.tsx
  src/app/club/_hooks/_quries/useGetLocalClubList.ts
  src/app/club/_hooks/_quries/useGetNewClubList.ts
  src/app/club/page.tsx
  src/app/club/types.tsx
  src/app/feed/[feedId]/_components/FeedDetailContentSection.tsx
  src/app/feed/[feedId]/_hooks/_mutations/usePostFeedComment.ts
  src/app/meeting/create/page.tsx
  src/mock/api/clubApi.js
  src/mock/handler.js
  src/mock/mockData/clubData.ts
  src/stories/ClubGenreList.stories.tsx
  src/stories/LocalClubListItem.stories.tsx
Labels: ✨Feature

#105 feat : Carousel 컴포넌트 추가
  package.json
  pnpm-lock.yaml
  src/_common/_components/Carousel/Shadcn_Carousel.tsx
  src/_common/_components/Carousel/index.tsx
  src/_common/_components/temp.tsx
  src/app/page.tsx
  src/stories/Carousel.stories.tsx
Labels: ✨Feature

#109 feat : 동호회 소개 게시글 페이지 구현
  next.config.js
  pnpm-lock.yaml
  src/app/club/[clubId]/_api/getClubDetail.ts
  src/app/club/[clubId]/_api/joinClub.ts
  src/app/club/[clubId]/_components/ClubIntroduceDetailSection.tsx
  src/app/club/[clubId]/_components/ClubIntroduceHeader.tsx
  src/app/club/[clubId]/_components/JoinClubModal.tsx
  src/app/club/[clubId]/_hooks/_mutations/useJoinClub.ts
  src/app/club/[clubId]/_hooks/_quries/useGetClubDetail.ts
  src/app/club/[clubId]/page.tsx
  src/app/club/[clubId]/types.ts
  src/app/club/_components/ClubGenreList.tsx
  src/app/club/_components/NewClubListItem.tsx
  src/app/club/page.tsx
  src/mock/api/clubApi.js
  src/mock/mockData/clubData.ts
Labels: ✨Feature

#111 feat : 동호회 생성 페이지 구현
  src/_common/_components/Chips/chip.tsx
  src/app/club/[clubId]/page.tsx
  src/app/club/_components/ClubFootBar.tsx
  src/app/club/_components/NewClubListItem.tsx
  src/app/club/create/_api/createClub.ts
  src/app/club/create/_components/CreateClubFunnelHeader.tsx
  src/app/club/create/_components/_funnels/ClubCategoryInput.tsx
  src/app/club/create/_components/_funnels/ClubCreateSuccess.tsx
  src/app/club/create/_components/_funnels/ClubLocationInput.tsx
  src/app/club/create/_components/_funnels/ClubMemberLimitInput.tsx
  src/app/club/create/_components/_funnels/ClubNameInput.tsx
  src/app/club/create/_components/_funnels/ClubScheduleInput.tsx
  src/app/club/create/_hooks/_mutations/useCreateClub.ts
  src/app/club/create/page.tsx
  src/app/club/page.tsx
  src/mock/api/clubApi.js
Labels: ✨Feature

#112 refactor & settings : Cypress 추가 및 E2E 테스트 코드 추가 & 유닛 TestCode 리펙토링
  cypress.config.ts
  cypress/e2e/feed.cy.ts
  cypress/e2e/feedCreate.cy.ts
  cypress/e2e/meetingCreate.cy.ts
  cypress/e2e/meetingDetail.cy.ts
  cypress/e2e/meetingManage.cy.ts
  cypress/support/e2e.ts
  package.json
  pnpm-lock.yaml
  src/_common/_components/DropBox/index.tsx
  src/_common/_components/Toast.tsx
  src/_common/_hooks/useFunnel/_test/useFunnel.spec.tsx
  src/_common/_hooks/useInfiniteScroll/_test/useInfiniteScroll.spec.tsx
  src/_common/_hooks/useModal/_test/useModal.test.tsx
  src/_common/_hooks/useToast/index.ts
  src/app/club/create/_components/CreateClubFunnelHeader.tsx
  src/app/feed/[feedId]/_components/FeedCommentInputBar.tsx
  src/app/feed/[feedId]/_components/FeedCommentSection.tsx
  src/app/feed/[feedId]/_components/FeedDetailContentSection.tsx
  src/app/feed/_components/FeedHeader.tsx
  src/app/feed/create/_components/_funnels/FeedCategoryInput.tsx
  src/app/feed/create/_components/_funnels/FeedContentInput.tsx
  src/app/feed/create/_components/_funnels/FeedTitleInput.tsx
  src/app/feed/create/page.tsx
  src/app/feed/types.ts
  src/app/manage/_components/CreatedMeetings/MeetingOptionModal.tsx
  src/app/manage/_components/CreatedMeetings/MyManagingMeetingItem.tsx
  src/app/manage/_components/CreatedMeetings/ParticipatorRefuseModal.tsx
  src/app/manage/_components/CreatedMeetings/index.tsx
  src/app/manage/_components/ParticipatingMeetings/ParticipatingMeetingsItem.tsx
  src/app/manage/_components/ParticipatingMeetings/index.tsx
  src/app/meeting/[detailPageId]/_api/participateMeeting.ts
  src/app/meeting/[detailPageId]/_components/MeetingParticipateModal.tsx
  src/app/meeting/[detailPageId]/_hooks/_quries/useGetMeetingDetail.ts
  src/app/meeting/[detailPageId]/page.tsx
  src/app/meeting/_components/FootBar.tsx
  src/app/meeting/create/_components/CreateMeetingFunnelHeader.tsx
  src/app/meeting/create/_components/_funnels/MeetingCategory.tsx
  src/app/meeting/create/_components/_funnels/MeetingCreateSuccess.tsx
  src/app/meeting/create/_components/_funnels/MeetingDate.tsx
  src/app/meeting/create/_components/_funnels/MeetingDetailInput.tsx
  src/app/meeting/create/_components/_funnels/MeetingPeopleInput.tsx
  src/app/meeting/create/_components/_funnels/MeetingPlace.tsx
  src/app/meeting/create/_components/_funnels/MeetingTime.tsx
  src/app/meeting/create/_components/_funnels/MeetingTitleInput.tsx
  src/mock/api/chatApi.ts
  src/mock/api/chatRoomApi.ts
  src/mock/api/meetingApi.js
  src/mock/browser.ts
  src/mock/http.js
  src/mock/mockData/feedData.ts
  src/stories/hooks/useFunnel.stories.tsx
  src/stories/hooks/useInfiniteScroll.stories.tsx
  src/stories/hooks/useModal.stories.tsx
Labels: ⚙Setting, 🔨Refactor

#115 setting : E2E 테스트 자동화
  .github/workflows/unit&E2Etest.yml
  cypress.config.ts
  pnpm-lock.yaml
  src/app/mypage/_hooks/_quries/useGetUserInform.ts
Labels: ⚙Setting
