Repository Network-office/Network-office-FE, pull requests merged in 2024-11, with the labels that each got.

#124 refactor : 네이버 지도 APi 최적화, 클러스터링 기능 추가
  .github/workflows/unit&E2Etest.yml
  cypress/e2e/feed.cy.ts
  pnpm-lock.yaml
  src/_common/_hooks/useNaverMap/_components/ClusterIcon.tsx
  src/_common/_hooks/useNaverMap/_components/ClusterModal.tsx
  src/_common/_hooks/useNaverMap/_components/NaverMapComponent.tsx
  src/_common/_hooks/useNaverMap/_utils/getMapBoundInMarker.ts
  src/_common/_hooks/useNaverMap/_utils/getMapBoundOutMarker.ts
  src/_common/_hooks/useNaverMap/index.tsx
  src/_common/_hooks/useNaverMap/types.ts
  src/app/chat/page.tsx
  src/app/kakao/_components/AvatarForm.tsx
  src/app/kakao/_components/NickNameForm.tsx
  src/app/kakao/_context/signinContext.tsx
  src/app/kakao/_hooks/_queries/useGetUserInfo.ts
  src/app/kakao/login/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/meeting/_components/ClusterMeetingsModal.tsx
  src/app/meeting/page.tsx
  src/app/meeting/types.ts
  src/app/mypage/_api/getUserInform.ts
  src/app/mypage/_components/MyPageClient.tsx
  src/app/mypage/page.tsx
  src/app/mypage/types.ts
  src/app/provider.tsx
  src/mock/mockData/commonData.ts
  src/stories/chatRoom/ChatRoomListWithTabs.stories.tsx
Labels: 🔨Refactor

#126 setting : EC2 배포 자동화 파이프라인 구현
  .github/workflows/EC2DepolymentUpdate.yml
  .github/workflows/testCi.yml
Labels: ⚙Setting

#131 feat: 내 정보 조회, 프로필 입력, 사진 업로드 API 연결
  next.config.js
  src/app/kakao/_api/auth/csrf/index.ts
  src/app/kakao/_components/AvatarForm.tsx
  src/app/kakao/_components/NickNameForm.tsx
  src/app/kakao/_hooks/_mutations/useKakaoMutation.ts
  src/app/kakao/_hooks/_mutations/useUpdateNickname.ts
  src/app/kakao/_hooks/_mutations/useUpdateProfile.ts
  src/app/kakao/login/[socialid]/page.tsx
  src/app/mypage/_api/getUserInform.ts
  src/app/mypage/_components/MyPageClient.tsx
  src/app/mypage/types.ts
  src/lib/http.ts
Labels: ✨Feature

#133 feat: 아래로 스크롤 기능 추가
  src/_common/_components/ScrollDown/index.tsx
  src/app/chat/[chatId]/_components/MyMessageGroup.tsx
  src/app/chat/[chatId]/_components/OtherMessageGroup.tsx
  src/app/chat/[chatId]/_hooks/_test/useChatScroll.spec.tsx
  src/app/chat/[chatId]/_hooks/useChatScroll.ts
  src/app/chat/[chatId]/_hooks/useChatScroll.tsx
  src/app/chat/[chatId]/page.tsx
Labels: ✨Feature

#122 feat: stomp mock 수정
  jest.polyfills.js
  package.json
  src/_common/_components/ScrollDown/index.tsx
  src/_common/_hooks/useIntersecting/index.ts
  src/app/chat/[chatId]/_apis/getChatHistory.ts
  src/app/chat/[chatId]/_components/ChatPageTopbar.tsx
  src/app/chat/[chatId]/_components/Message/MessageContent.tsx
  src/app/chat/[chatId]/_components/MyMessageGroup.tsx
  src/app/chat/[chatId]/_components/OtherMessageGroup.tsx
  src/app/chat/[chatId]/_components/_tests/Message.spec.tsx
  src/app/chat/[chatId]/_components/_tests/MessageGroup.spec.tsx
  src/app/chat/[chatId]/_components/types.ts
  src/app/chat/[chatId]/_hooks/_test/useChatScroll.spec.tsx
  src/app/chat/[chatId]/_hooks/_test/useStomp.spec.tsx
  src/app/chat/[chatId]/_hooks/useChatScroll.tsx
  src/app/chat/[chatId]/_hooks/useFetchChatHistory.ts
  src/app/chat/[chatId]/_hooks/useStomp.ts
  src/app/chat/[chatId]/_test/page.spec.tsx
  src/app/chat/[chatId]/_utils/addMessageToChatHistory.spec.ts
  src/app/chat/[chatId]/_utils/addMessageToChatHistory.ts
  src/app/chat/[chatId]/layout.tsx
  src/app/chat/[chatId]/page.tsx
  src/app/chat/_apis/getChatRoomList.ts
  src/app/chat/_tests/chatRoomPage.spec.tsx
  src/app/chat/page.tsx
  src/components/ui/textarea.tsx
  src/mock/api/chatApi.ts
  src/mock/api/chatRoomApi.ts
  src/mock/mockData/chatHistoryData.ts
  src/mock/mockData/chatMessageData.ts
Labels: 🔨Refactor
